from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QApplication, QMainWindow, QInputDialog

class UIMain(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 419)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(237, 255, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 255, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 255, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        MainWindow.setPalette(palette)
        MainWindow.setWindowTitle("New Window")
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 401, 30))
        font = QtGui.QFont()
        font.setFamily("Proxima Nova")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_create = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_create.setGeometry(QtCore.QRect(30, 60, 161, 28))
        self.pushButton_create.setObjectName("pushButton_create")
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(30, 100, 161, 28))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_show = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_show.setGeometry(QtCore.QRect(30, 170, 161, 28))
        self.pushButton_show.setObjectName("pushButton_show")
        self.pushButton_searchStudent = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_searchStudent.setGeometry(QtCore.QRect(210, 170, 161, 28))
        self.pushButton_searchStudent.setObjectName("pushButton_searchStudent")
        self.pushButton_contDelete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_contDelete.setGeometry(QtCore.QRect(30, 210, 161, 28))
        self.pushButton_contDelete.setObjectName("pushButton_contDelete")
        self.pushButton_allContDelete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_allContDelete.setGeometry(QtCore.QRect(210, 210, 161, 28))
        self.pushButton_allContDelete.setObjectName("pushButton_allContDelete")
        self.pushButton_addStudent = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addStudent.setGeometry(QtCore.QRect(30, 280, 161, 28))
        self.pushButton_addStudent.setObjectName("pushButton_addStudent")
        self.pushButton_addAttend = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addAttend.setGeometry(QtCore.QRect(210, 280, 161, 28))
        self.pushButton_addAttend.setObjectName("pushButton_addAttend")
        self.pushButton_editStudent = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_editStudent.setGeometry(QtCore.QRect(30, 320, 161, 28))
        self.pushButton_editStudent.setObjectName("pushButton_editStudent")
        self.pushButton_deleteStudent = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_deleteStudent.setGeometry(QtCore.QRect(30, 360, 161, 28))
        self.pushButton_deleteStudent.setObjectName("pushButton_deleteStudent")
        self.pushButton_deleteAttend = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_deleteAttend.setGeometry(QtCore.QRect(210, 320, 161, 28))
        self.pushButton_deleteAttend.setObjectName("pushButton_deleteAttend")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "My super GUI for super DB"))
        self.pushButton_create.setText(_translate("MainWindow", "Create database"))
        self.pushButton_delete.setText(_translate("MainWindow", "Delete database"))
        self.pushButton_show.setText(_translate("MainWindow", "Show content"))
        self.pushButton_contDelete.setText(_translate("MainWindow", "Delete content"))
        self.pushButton_allContDelete.setText(_translate("MainWindow", "Delete all content"))
        self.pushButton_addStudent.setText(_translate("MainWindow", "Add student"))
        self.pushButton_addAttend.setText(_translate("MainWindow", "Sign up to lesson"))
        self.pushButton_editStudent.setText(_translate("MainWindow", "Edit student"))
        self.pushButton_deleteStudent.setText(_translate("MainWindow", "Delete student"))
        self.pushButton_deleteAttend.setText(_translate("MainWindow", "Sing out from lesson"))
        self.pushButton_searchStudent.setText(_translate("MainWindow", "Search for student"))
